### ISSUE TITLE
Ability to unregister and reload patches

### ISSUE THREAD

**Issue by mrharris** [christophercrouzet/gorilla#1]
Hi
Would it be possible to add an unregister_extensions() function? Or have the register_extensions function do a reload() of the packages passed into it? I think it would speed up developing with gorilla and help with troubleshooting
Thanks for the awesome module
Luke

**Comment by christophercrouzet** [comment]
Hi Luke!

Theorically it should be possible to add a sort of undo functionality but in practice I'm not sure if that would be very recommandable. I mean, it's already not so clean to do monkey patching in the first place, so patching and unpatching a same object over and over again seems like it could easily get out of control.

As for the module reloading function, this is out of the scope of this library but this is exactly the approach that I chose to speed up development when working on the [banana.maya](https://github.com/christophercrouzet/banana.maya) library. I ended up writing a `unload_user_modules()` function that I would call at the begin of my code, and then I would call again the gorilla patching method to patch my latest changes on a fresh instance of the reloaded modules.

The cool thing about it is that it reloads ALL the modules located in your home directory, if that's where you put your Python sources, but you could easily rewrite it to fit your needs. Here it is:
```Python
def unload_user_modules():
    module_names = []
    home_path = os.path.expanduser('~')
    for name, module in sys.modules.iteritems():
        if getattr(module, '__file__', '').startswith(home_path):
            module_names.append(name)

    for name in module_names:
        del sys.modules[name]
```

And here's an example of its usage at the begin of a script to run:
```Python
import utils
utils.unload_user_modules()

import banana.maya
banana.maya.patch()

[...]
```

I hope it helps, cheers!

**Comment by mrharris** [comment]
Thanks Christopher I'll try with this!

**Comment by jayvdb** [comment]
unpatch support would be useful, especially for use with a context manager.
https://pypi.org/project/python-monkey-business/ and https://pypi.org/project/patchy/ support it.

**Comment by christophercrouzet** [comment]
Hello @jayvdb, thanks for chiming in!

Would you have some use cases to share that could help me to understand where unpatching could be useful?

**Comment by jayvdb** [comment]
https://github.com/streeter/django-db-readonly/pull/22 is the case I was working on where it would be nice to use a managed toolkit for the patching, and a comment there shows another project doing similar patch/unpatch inside context managers.

https://github.com/bskinn/stdio-mgr is another example of a project I've worked on that comes to mind, where nestable context managers needed to patch another library.

**Comment by christophercrouzet** [comment]
Hello @jayvdb,

I guess this won't cost anything to implement it so here it is: #4!

Please let me know if that would work for you!
