### ISSUE TITLE
Projects using gorilla

### ISSUE THREAD

**Issue by hhoeflin** [christophercrouzet/gorilla#3]
Hi,

your gorilla project is now used by mlflow. Just thought you may want to mention it in your "Out there" part. (autolog functionality)

**Comment by christophercrouzet** [comment]
Hello @hhoeflin, thanks for letting me know!

This has to be the first time that my open sourced code is being useful to someone else than me, haha! :champagne: 

This has been addresed in the commit 78e16570ac8c977840a121782e6d147f003586b9 :heart:
