### ISSUE TITLE
Do you plan to register the latest version with PyPI?

### ISSUE THREAD

**Issue by lm-takumi-nakaso** [christophercrouzet/gorilla#5]
Do you plan to register the latest version with [PyPI](https://pypi.org/project/gorilla/)?
I would like to use [gorilla.revert](https://gorilla.readthedocs.io/en/latest/core.html#gorilla.revert) function.

**Comment by christophercrouzet** [comment]
Hello @lm-takumi-nakaso,

Sure thing, I'll try doing that over the week-end!

If I end up forgetting, please don't hesitate to ping me again! :blush:

**Comment by lm-takumi-nakaso** [comment]
@christophercrouzet Thank you so much!
I'm looking forward to it.

**Comment by christophercrouzet** [comment]
Hello @lm-takumi-nakaso!

I've now released gorilla 0.4.0 on PyPI, see https://pypi.org/project/gorilla/0.4.0.

Please let me know how it goes! :blush:

**Comment by lm-takumi-nakaso** [comment]
@christophercrouzet I have confirmed that the update and revert were performed on PyPI in gorilla. Thank you for your support!

**Comment by christophercrouzet** [comment]
Awesome, thanks for letting me know! Cheers!
